[package]
name = "tote"
version = "0.1.0"
authors = ["omprakashsridharan <omprakashsridharan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "18.2.0"
clap = "2.33.1"
prettytable-rs = "^0.8"
